Repository ansible-collections/cisco.nxos, pull requests merged in 2020-05, with the labels that each got.

#43 Updated deleted state for nxos_acls
  plugins/module_utils/network/nxos/config/acls/acls.py
  tests/integration/targets/nxos_acls/tests/cli/deleted.yml
  tests/unit/modules/network/nxos/test_nxos_acls.py
Labels: gate

#42 Add new states to nxos_lldp_global
  plugins/module_utils/network/nxos/argspec/lldp_global/lldp_global.py
  plugins/module_utils/network/nxos/config/lldp_global/lldp_global.py
  plugins/modules/nxos_lldp_global.py
  tests/integration/targets/nxos_lldp_global/defaults/main.yaml
  tests/integration/targets/nxos_lldp_global/tasks/cli.yaml
  tests/integration/targets/nxos_lldp_global/tests/common/_populate_config.yml
  tests/integration/targets/nxos_lldp_global/tests/common/_remove_config.yml
  tests/integration/targets/nxos_lldp_global/tests/common/deleted.yml
  tests/integration/targets/nxos_lldp_global/tests/common/gathered.yml
  tests/integration/targets/nxos_lldp_global/tests/common/merged.yml
  tests/integration/targets/nxos_lldp_global/tests/common/parsed.yml
  tests/integration/targets/nxos_lldp_global/tests/common/rendered.yml
  tests/integration/targets/nxos_lldp_global/tests/common/replaced.yml
  tests/integration/targets/nxos_lldp_global/vars/main.yml
Labels: gate

#12 NX-OS static routes module
  plugins/module_utils/network/nxos/argspec/static_routes/__init__.py
  plugins/module_utils/network/nxos/argspec/static_routes/static_routes.py
  plugins/module_utils/network/nxos/config/static_routes/__init__.py
  plugins/module_utils/network/nxos/config/static_routes/static_routes.py
  plugins/module_utils/network/nxos/facts/facts.py
  plugins/module_utils/network/nxos/facts/static_routes/__init__.py
  plugins/module_utils/network/nxos/facts/static_routes/static_routes.py
  plugins/modules/nxos_static_routes.py
  tests/.gitignore
  tests/integration/targets/nxos_static_routes/defaults/main.yaml
  tests/integration/targets/nxos_static_routes/meta/main.yml
  tests/integration/targets/nxos_static_routes/tasks/cli.yaml
  tests/integration/targets/nxos_static_routes/tasks/main.yaml
  tests/integration/targets/nxos_static_routes/tests/common/_populate_config.yaml
  tests/integration/targets/nxos_static_routes/tests/common/_remove_config.yaml
  tests/integration/targets/nxos_static_routes/tests/common/deleted.yml
  tests/integration/targets/nxos_static_routes/tests/common/gathered.yml
  tests/integration/targets/nxos_static_routes/tests/common/merged.yml
  tests/integration/targets/nxos_static_routes/tests/common/overridden.yml
  tests/integration/targets/nxos_static_routes/tests/common/parsed.yml
  tests/integration/targets/nxos_static_routes/tests/common/rendered.yml
  tests/integration/targets/nxos_static_routes/tests/common/replaced.yml
  tests/integration/targets/nxos_static_routes/tests/common/rtt.yml
  tests/integration/targets/nxos_static_routes/vars/main.yml
  tests/unit/modules/network/nxos/test_nxos_static_routes.py
Labels: gate

#37 Add new states to nxos_l2_interfaces
  plugins/module_utils/network/nxos/argspec/l2_interfaces/l2_interfaces.py
  plugins/module_utils/network/nxos/config/l2_interfaces/l2_interfaces.py
  plugins/modules/nxos_l2_interfaces.py
  tests/integration/targets/nxos_l2_interfaces/defaults/main.yaml
  tests/integration/targets/nxos_l2_interfaces/tasks/cli.yaml
  tests/integration/targets/nxos_l2_interfaces/tasks/nxapi.yaml
  tests/integration/targets/nxos_l2_interfaces/tests/common/_populate_config.yaml
  tests/integration/targets/nxos_l2_interfaces/tests/common/_remove_config.yaml
  tests/integration/targets/nxos_l2_interfaces/tests/common/deleted.yaml
  tests/integration/targets/nxos_l2_interfaces/tests/common/empty_config.yaml
  tests/integration/targets/nxos_l2_interfaces/tests/common/gathered.yaml
  tests/integration/targets/nxos_l2_interfaces/tests/common/merged.yaml
  tests/integration/targets/nxos_l2_interfaces/tests/common/overridden.yaml
  tests/integration/targets/nxos_l2_interfaces/tests/common/parsed.yaml
  tests/integration/targets/nxos_l2_interfaces/tests/common/rendered.yaml
  tests/integration/targets/nxos_l2_interfaces/tests/common/replaced.yaml
  tests/integration/targets/nxos_l2_interfaces/vars/main.yml
Labels: gate

#53 Documentation fix for nxos_acls
  plugins/modules/nxos_acls.py
Labels: gate

#47 Add new states to nxos_l3_interfaces
  plugins/module_utils/network/nxos/argspec/l3_interfaces/l3_interfaces.py
  plugins/module_utils/network/nxos/config/l3_interfaces/l3_interfaces.py
  plugins/module_utils/network/nxos/utils/utils.py
  plugins/modules/nxos_l3_interfaces.py
  tests/integration/targets/nxos_l3_interfaces/defaults/main.yaml
  tests/integration/targets/nxos_l3_interfaces/tasks/cli.yaml
  tests/integration/targets/nxos_l3_interfaces/tests/common/_populate_config.yaml
  tests/integration/targets/nxos_l3_interfaces/tests/common/_remove_config.yaml
  tests/integration/targets/nxos_l3_interfaces/tests/common/deleted.yaml
  tests/integration/targets/nxos_l3_interfaces/tests/common/empty_config.yaml
  tests/integration/targets/nxos_l3_interfaces/tests/common/gathered.yaml
  tests/integration/targets/nxos_l3_interfaces/tests/common/merged.yaml
  tests/integration/targets/nxos_l3_interfaces/tests/common/overridden.yaml
  tests/integration/targets/nxos_l3_interfaces/tests/common/parsed.yaml
  tests/integration/targets/nxos_l3_interfaces/tests/common/rendered.yaml
  tests/integration/targets/nxos_l3_interfaces/tests/common/replaced.yaml
  tests/integration/targets/nxos_l3_interfaces/vars/main.yml
  tests/unit/modules/network/nxos/test_nxos_l3_interfaces.py
Labels: gate

#44 Add new states to nxos_bfd_interfaces
  plugins/module_utils/network/nxos/argspec/bfd_interfaces/bfd_interfaces.py
  plugins/module_utils/network/nxos/config/bfd_interfaces/bfd_interfaces.py
  plugins/modules/nxos_bfd_interfaces.py
  tests/integration/targets/nxos_bfd_interfaces/defaults/main.yaml
  tests/integration/targets/nxos_bfd_interfaces/tasks/cli.yaml
  tests/integration/targets/nxos_bfd_interfaces/tasks/main.yaml
  tests/integration/targets/nxos_bfd_interfaces/tasks/nxapi.yaml
  tests/integration/targets/nxos_bfd_interfaces/tests/common/_populate_config.yaml
  tests/integration/targets/nxos_bfd_interfaces/tests/common/_remove_config.yaml
  tests/integration/targets/nxos_bfd_interfaces/tests/common/deleted.yaml
  tests/integration/targets/nxos_bfd_interfaces/tests/common/empty_config.yaml
  tests/integration/targets/nxos_bfd_interfaces/tests/common/gathered.yaml
  tests/integration/targets/nxos_bfd_interfaces/tests/common/merged.yaml
  tests/integration/targets/nxos_bfd_interfaces/tests/common/overridden.yaml
  tests/integration/targets/nxos_bfd_interfaces/tests/common/parsed.yaml
  tests/integration/targets/nxos_bfd_interfaces/tests/common/rendered.yaml
  tests/integration/targets/nxos_bfd_interfaces/tests/common/replaced.yaml
  tests/integration/targets/nxos_bfd_interfaces/vars/main.yml
Labels: gate

#40 Add new states for nxos_lag_interfaces
  plugins/module_utils/network/nxos/argspec/lag_interfaces/lag_interfaces.py
  plugins/module_utils/network/nxos/config/lag_interfaces/lag_interfaces.py
  plugins/module_utils/network/nxos/facts/lag_interfaces/lag_interfaces.py
  plugins/modules/nxos_lag_interfaces.py
  tests/integration/targets/nxos_lag_interfaces/defaults/main.yaml
  tests/integration/targets/nxos_lag_interfaces/tasks/cli.yaml
  tests/integration/targets/nxos_lag_interfaces/tests/common/_populate_config.yaml
  tests/integration/targets/nxos_lag_interfaces/tests/common/_remove_config.yaml
  tests/integration/targets/nxos_lag_interfaces/tests/common/deleted.yaml
  tests/integration/targets/nxos_lag_interfaces/tests/common/empty_config.yaml
  tests/integration/targets/nxos_lag_interfaces/tests/common/gathered.yaml
  tests/integration/targets/nxos_lag_interfaces/tests/common/merged.yaml
  tests/integration/targets/nxos_lag_interfaces/tests/common/overridden.yaml
  tests/integration/targets/nxos_lag_interfaces/tests/common/parsed.yaml
  tests/integration/targets/nxos_lag_interfaces/tests/common/rendered.yaml
  tests/integration/targets/nxos_lag_interfaces/tests/common/replaced.yaml
  tests/integration/targets/nxos_lag_interfaces/vars/main.yml
Labels: gate

#41 Add new states to nxos_lacp_interfaces
  plugins/module_utils/network/nxos/argspec/lacp_interfaces/lacp_interfaces.py
  plugins/module_utils/network/nxos/config/lacp_interfaces/lacp_interfaces.py
  plugins/module_utils/network/nxos/facts/lacp_interfaces/lacp_interfaces.py
  plugins/modules/nxos_lacp_interfaces.py
  tests/integration/targets/nxos_lacp_interfaces/defaults/main.yaml
  tests/integration/targets/nxos_lacp_interfaces/tasks/cli.yaml
  tests/integration/targets/nxos_lacp_interfaces/tests/common/_populate_config.yaml
  tests/integration/targets/nxos_lacp_interfaces/tests/common/_remove_config.yaml
  tests/integration/targets/nxos_lacp_interfaces/tests/common/deleted.yaml
  tests/integration/targets/nxos_lacp_interfaces/tests/common/empty_config.yaml
  tests/integration/targets/nxos_lacp_interfaces/tests/common/gathered.yaml
  tests/integration/targets/nxos_lacp_interfaces/tests/common/merged.yaml
  tests/integration/targets/nxos_lacp_interfaces/tests/common/overridden.yaml
  tests/integration/targets/nxos_lacp_interfaces/tests/common/parsed.yaml
  tests/integration/targets/nxos_lacp_interfaces/tests/common/rendered.yaml
  tests/integration/targets/nxos_lacp_interfaces/tests/common/replaced.yaml
  tests/integration/targets/nxos_lacp_interfaces/vars/main.yml
Labels: gate

#45 Add new states to nxos_hsrp_interfaces
  plugins/module_utils/network/nxos/argspec/hsrp_interfaces/hsrp_interfaces.py
  plugins/module_utils/network/nxos/config/hsrp_interfaces/hsrp_interfaces.py
  plugins/modules/nxos_hsrp_interfaces.py
  tests/integration/targets/nxos_hsrp_interfaces/defaults/main.yaml
  tests/integration/targets/nxos_hsrp_interfaces/tasks/cli.yaml
  tests/integration/targets/nxos_hsrp_interfaces/tasks/main.yaml
  tests/integration/targets/nxos_hsrp_interfaces/tasks/nxapi.yaml
  tests/integration/targets/nxos_hsrp_interfaces/tests/common/_populate_config.yaml
  tests/integration/targets/nxos_hsrp_interfaces/tests/common/_remove_config.yaml
  tests/integration/targets/nxos_hsrp_interfaces/tests/common/deleted.yaml
  tests/integration/targets/nxos_hsrp_interfaces/tests/common/empty_config.yaml
  tests/integration/targets/nxos_hsrp_interfaces/tests/common/gathered.yaml
  tests/integration/targets/nxos_hsrp_interfaces/tests/common/merged.yaml
  tests/integration/targets/nxos_hsrp_interfaces/tests/common/overridden.yaml
  tests/integration/targets/nxos_hsrp_interfaces/tests/common/parsed.yaml
  tests/integration/targets/nxos_hsrp_interfaces/tests/common/rendered.yaml
  tests/integration/targets/nxos_hsrp_interfaces/tests/common/replaced.yaml
  tests/integration/targets/nxos_hsrp_interfaces/vars/main.yml
Labels: gate

#56 Fix system default generation
  plugins/module_utils/network/nxos/facts/interfaces/interfaces.py
  tests/integration/targets/nxos_interfaces/tests/common/merged.yaml
Labels: gate

#55 Fix issue with state replaced
  plugins/module_utils/network/nxos/config/l2_interfaces/l2_interfaces.py
  tests/integration/targets/nxos_l2_interfaces/tests/common/replaced.yaml
Labels: gate

#51 update nxos readme
  README.md
  README.rst
  galaxy.yml
Labels: gate

#52 nxos_file_copy test fixes
  tests/integration/targets/nxos_file_copy/fixtures/data.cfg
  tests/integration/targets/nxos_file_copy/tasks/main.yaml
  tests/integration/targets/nxos_file_copy/tests/cli/negative.yaml
  tests/integration/targets/nxos_file_copy/tests/cli/sanity.yaml
Labels: gate

#59 Republish nxos_file_copy changes
  plugins/action/nxos_file_copy.py
  tests/integration/targets/nxos_file_copy/tests/nxapi/badtransport.yaml
Labels: gate

#57 Add new states to nxos_interfaces
  plugins/module_utils/network/nxos/argspec/interfaces/interfaces.py
  plugins/module_utils/network/nxos/config/interfaces/interfaces.py
  plugins/module_utils/network/nxos/facts/interfaces/interfaces.py
  plugins/modules/nxos_interfaces.py
  tests/integration/targets/nxos_interfaces/defaults/main.yaml
  tests/integration/targets/nxos_interfaces/tasks/cli.yaml
  tests/integration/targets/nxos_interfaces/tasks/nxapi.yaml
  tests/integration/targets/nxos_interfaces/tests/common/_populate_config.yaml
  tests/integration/targets/nxos_interfaces/tests/common/_remove_config.yaml
  tests/integration/targets/nxos_interfaces/tests/common/empty_config.yaml
  tests/integration/targets/nxos_interfaces/tests/common/gathered.yaml
  tests/integration/targets/nxos_interfaces/tests/common/parsed.yaml
  tests/integration/targets/nxos_interfaces/tests/common/rendered.yaml
  tests/integration/targets/nxos_interfaces/vars/main.yml
  tests/integration/targets/nxos_lacp_interfaces/tests/common/_populate_config.yaml
Labels: gate

#62 Cleanup loopback interfaces properly
  tests/integration/targets/nxos_interfaces/tests/common/_remove_config.yaml
Labels: gate

#58 httpapi enable issue
  plugins/httpapi/nxos.py
Labels: gate

#63 Update nxos_acls
  plugins/module_utils/network/nxos/config/acls/acls.py
  plugins/modules/nxos_acls.py
Labels: gate

#65 Add new states to nxos_vlans
  plugins/module_utils/network/nxos/argspec/vlans/vlans.py
  plugins/module_utils/network/nxos/config/vlans/vlans.py
  plugins/module_utils/network/nxos/facts/vlans/vlans.py
  plugins/modules/nxos_vlans.py
  tests/integration/targets/nxos_vlans/defaults/main.yaml
  tests/integration/targets/nxos_vlans/fixtures/parsed.cfg
  tests/integration/targets/nxos_vlans/tasks/cli.yaml
  tests/integration/targets/nxos_vlans/tests/common/_populate_config.yaml
  tests/integration/targets/nxos_vlans/tests/common/_remove_config.yaml
  tests/integration/targets/nxos_vlans/tests/common/deleted.yaml
  tests/integration/targets/nxos_vlans/tests/common/empty_config.yaml
  tests/integration/targets/nxos_vlans/tests/common/gathered.yaml
  tests/integration/targets/nxos_vlans/tests/common/merged.yaml
  tests/integration/targets/nxos_vlans/tests/common/overridden.yaml
  tests/integration/targets/nxos_vlans/tests/common/parsed.yaml
  tests/integration/targets/nxos_vlans/tests/common/rendered.yaml
  tests/integration/targets/nxos_vlans/tests/common/replaced.yaml
  tests/integration/targets/nxos_vlans/vars/main.yml
Labels: gate

#49 Updated nxos.py terminal plugin on_become
  plugins/terminal/nxos.py
Labels: gate

#66 Update acl_interfaces
  plugins/module_utils/network/nxos/config/acl_interfaces/acl_interfaces.py
  plugins/modules/nxos_acl_interfaces.py
  tests/integration/targets/nxos_acl_interfaces/tests/common/deleted.yml
Labels: gate

#70 Add symlinks to mds modules
  plugins/modules/nxos_devicealias.py
  plugins/modules/nxos_vsan.py
  plugins/modules/nxos_zone_zoneset.py
Labels: gate

#73 [cisco.nxos] Add test requirement for coverage
  test-requirements.txt
Labels: gate

#72 Ignore enable in httpapi as it is not supported on nxapi
  plugins/httpapi/nxos.py
Labels: gate

#61 Check feature privilege status only if priv escalation is required
  plugins/terminal/nxos.py
Labels: bug, gate

#67 Add runtime.yml file
  meta/runtime.yml
Labels: feature, gate
