Repository ansible-collections/cisco.nxos, pull requests merged in 2020-06, with the labels that each got.

#33 Add nxos_ospfv2 Resource Module
  .gitignore
  plugins/cliconf/nxos.py
  plugins/httpapi/nxos.py
  plugins/module_utils/network/nxos/argspec/ospfv2/__init__.py
  plugins/module_utils/network/nxos/argspec/ospfv2/ospfv2.py
  plugins/module_utils/network/nxos/config/ospfv2/__init__.py
  plugins/module_utils/network/nxos/config/ospfv2/ospfv2.py
  plugins/module_utils/network/nxos/facts/facts.py
  plugins/module_utils/network/nxos/facts/ospfv2/__init__.py
  plugins/module_utils/network/nxos/facts/ospfv2/ospfv2.py
  plugins/module_utils/network/nxos/rm_templates/__init__.py
  plugins/module_utils/network/nxos/rm_templates/ospfv2.py
  plugins/modules/nxos_facts.py
  plugins/modules/nxos_ospf.py
  plugins/modules/nxos_ospfv2.py
  plugins/modules/storage/nxos_devicealias.py
  plugins/modules/storage/nxos_vsan.py
  plugins/modules/storage/nxos_zone_zoneset.py
  tests/integration/targets/nxos_ospfv2/defaults/main.yaml
  tests/integration/targets/nxos_ospfv2/meta/main.yml
  tests/integration/targets/nxos_ospfv2/tasks/cli.yaml
  tests/integration/targets/nxos_ospfv2/tasks/main.yaml
  tests/integration/targets/nxos_ospfv2/tasks/nxapi.yaml
  tests/integration/targets/nxos_ospfv2/tests/common/_populate_config.yaml
  tests/integration/targets/nxos_ospfv2/tests/common/_remove_config.yaml
  tests/integration/targets/nxos_ospfv2/tests/common/deleted.yaml
  tests/integration/targets/nxos_ospfv2/tests/common/fixtures/parsed.cfg
  tests/integration/targets/nxos_ospfv2/tests/common/gathered.yaml
  tests/integration/targets/nxos_ospfv2/tests/common/merged.yaml
  tests/integration/targets/nxos_ospfv2/tests/common/overridden.yaml
  tests/integration/targets/nxos_ospfv2/tests/common/parsed.yaml
  tests/integration/targets/nxos_ospfv2/tests/common/rendered.yaml
  tests/integration/targets/nxos_ospfv2/tests/common/replaced.yaml
  tests/integration/targets/nxos_ospfv2/vars/main.yml
  tests/unit/modules/network/nxos/test_nxos_ospfv2.py
Labels: feature, gate

#68 Fix for vdc with no interface in N7K
  plugins/module_utils/network/nxos/facts/legacy/base.py
Labels: bug, gate

#76 Add nxos_smoke tests back
  plugins/action/nxos.py
  tests/integration/targets/nxos_smoke/defaults/main.yaml
  tests/integration/targets/nxos_smoke/meta/main.yml
  tests/integration/targets/nxos_smoke/tasks/cli.yaml
  tests/integration/targets/nxos_smoke/tasks/main.yaml
  tests/integration/targets/nxos_smoke/tasks/nxapi.yaml
  tests/integration/targets/nxos_smoke/tests/cli/misc_tests.yaml
  tests/integration/targets/nxos_smoke/tests/common/common_config.yaml
  tests/integration/targets/nxos_smoke/tests/common/common_utils.yaml
  tests/integration/targets/nxos_smoke/tests/common/misc_tests.yaml
Labels: gate

#77 Woah, we really should not be promoting provider for NX-API
  plugins/doc_fragments/nxos.py
Labels: gate

#85 Update runtime.yml with removal_date
  meta/runtime.yml
Labels: gate

#78 Fix for #46
  plugins/cliconf/nxos.py
Labels: gate

#88 Update runtime.yml requires_ansible version
  meta/runtime.yml
Labels: gate

#79 Streamline l2_interfaces and l3_interfaces
  plugins/module_utils/network/nxos/config/l3_interfaces/l3_interfaces.py
  plugins/module_utils/network/nxos/facts/l2_interfaces/l2_interfaces.py
  plugins/module_utils/network/nxos/facts/l3_interfaces/l3_interfaces.py
  plugins/modules/nxos_l3_interfaces.py
  tests/integration/targets/nxos_l2_interfaces/tests/common/deleted.yaml
  tests/integration/targets/nxos_l2_interfaces/tests/common/gathered.yaml
  tests/integration/targets/nxos_l2_interfaces/tests/common/merged.yaml
  tests/integration/targets/nxos_l2_interfaces/tests/common/rendered.yaml
  tests/integration/targets/nxos_l2_interfaces/tests/common/rtt.yaml
  tests/integration/targets/nxos_l3_interfaces/tasks/main.yaml
  tests/integration/targets/nxos_l3_interfaces/tasks/nxapi.yaml
  tests/integration/targets/nxos_l3_interfaces/tests/common/deleted.yaml
  tests/integration/targets/nxos_l3_interfaces/tests/common/gathered.yaml
  tests/integration/targets/nxos_l3_interfaces/tests/common/merged.yaml
  tests/integration/targets/nxos_l3_interfaces/tests/common/overridden.yaml
  tests/integration/targets/nxos_l3_interfaces/tests/common/parsed.yaml
  tests/integration/targets/nxos_l3_interfaces/tests/common/rendered.yaml
  tests/integration/targets/nxos_l3_interfaces/tests/common/replaced.yaml
  tests/integration/targets/nxos_l3_interfaces/tests/common/rtt.yaml
  tests/integration/targets/nxos_l3_interfaces/vars/main.yml
  tests/unit/modules/network/nxos/test_nxos_l3_interfaces.py
Labels: gate

#91 Fixed #90, 8.4(2) introduced single-session feature, so pattern to ge…
  plugins/modules/storage/nxos_zone_zoneset.py
  tests/integration/targets/nxos_devicealias/tasks/main.yaml
  tests/integration/targets/nxos_vsan/tasks/main.yaml
  tests/integration/targets/nxos_zone_zoneset/tasks/main.yaml
  tests/integration/targets/nxos_zone_zoneset/tests/common/sanity.yaml
  tests/unit/modules/network/nxos/storage/test_nxos_zone_zoneset.py
Labels: gate

#96 add link to contributor guide etc
  README.md
Labels: gate

#99 Add changelog files
  changelogs/CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/config.yaml
  changelogs/fragments/99-add-change-log-1.0.0.yaml
Labels: gate

#102 Fix nxos_interfaces state overridden & replaced
  changelogs/102-fix-nxos_interfaces-states.yaml
  plugins/module_utils/network/nxos/config/interfaces/interfaces.py
  tests/integration/targets/nxos_interfaces/tests/common/replaced.yaml
Labels: gate
