Repository ansible-collections/cisco.nxos, pull requests merged in 2022-04, with the labels that each got.

#453 Prepare for release v2.9.1
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/fix_nxos_vlans.yaml
  changelogs/fragments/fix_sanity.yaml
  changelogs/fragments/module_docs_support_for_cisco_mds.yaml
  changelogs/fragments/ntp_global.yaml
  changelogs/fragments/runtime.yaml
  changelogs/fragments/sanity.yaml
  changelogs/fragments/snmp_server.yaml
  changelogs/fragments/tox.yaml
Labels: gate, mergeit

#451 Fix tests for image upgrade
  README.md
  changelogs/fragments/fix_ci.yaml
  tests/integration/targets/nxos_acl_interfaces/tasks/main.yaml
  tests/integration/targets/nxos_file_copy/tests/cli/negative.yaml
  tests/integration/targets/nxos_file_copy/tests/cli/sanity.yaml
  tests/integration/targets/nxos_file_copy/tests/nxapi/badtransport.yaml
  tests/integration/targets/nxos_lag_interfaces/tasks/main.yaml
  tests/integration/targets/nxos_logging/tests/common/basic.yaml
  tests/integration/targets/nxos_ntp_global/tests/common/merged.yaml
  tests/integration/targets/nxos_ntp_global/tests/common/overridden.yaml
  tests/integration/targets/nxos_ntp_global/tests/common/rendered.yaml
  tests/integration/targets/nxos_ntp_global/tests/common/replaced.yaml
  tests/integration/targets/nxos_ntp_global/vars/main.yml
  tests/integration/targets/nxos_prefix_lists/tests/common/_remove_config.yaml
  tests/integration/targets/nxos_smoke/tasks/cli.yaml
  tests/integration/targets/nxos_smoke/tasks/nxapi.yaml
  tests/integration/targets/nxos_smoke/tests/common/common_utils.yaml
  tests/integration/targets/nxos_snmp_server/tasks/main.yaml
  tests/integration/targets/nxos_snmp_server/tests/common/merged.yaml
  tests/integration/targets/nxos_snmp_server/tests/common/overridden.yaml
  tests/integration/targets/nxos_snmp_server/tests/common/rendered.yaml
  tests/integration/targets/nxos_snmp_server/tests/common/replaced.yaml
  tests/integration/targets/nxos_snmp_server/vars/main.yml
  tests/integration/targets/nxos_telemetry/tasks/main.yaml
  tests/integration/targets/nxos_telemetry/vars/main.yaml
  tests/integration/targets/prepare_nxos_tests/tasks/main.yml
Labels: mergeit

#461 [facts] change default subset to min
  changelogs/fragments/nxos_facts.yaml
  docs/cisco.nxos.nxos_facts_module.rst
  plugins/module_utils/network/nxos/argspec/facts/facts.py
  plugins/modules/nxos_facts.py
  tests/integration/targets/nxos_facts/tests/common/default_facts.yaml
Labels: blocks_release, mergeit

#458 fix slow stderr regex search
  changelogs/fragments/stderr.yaml
  plugins/terminal/nxos.py
Labels: mergeit

#419 updated references of base plugins to netcommon
  changelogs/fragments/netcommon_ref_update.yaml
  galaxy.yml
  plugins/httpapi/nxos.py
  plugins/netconf/nxos.py
  plugins/terminal/nxos.py
Labels: blocks_release, mergeit

#475 [ntp_global] fail when using missing auth key
  changelogs/fragments/ntp.yaml
  plugins/terminal/nxos.py
  tests/integration/targets/nxos_ntp_global/tests/common/merged.yaml
Labels: mergeit

#464 [lag_interfaces] fix overriden for channels with no members
  changelogs/fragments/lag_interfaces.yaml
  plugins/module_utils/network/nxos/config/lag_interfaces/lag_interfaces.py
  tests/integration/targets/nxos_lag_interfaces/tests/common/_remove_config.yaml
  tests/integration/targets/nxos_lag_interfaces/tests/common/merged.yaml
  tests/integration/targets/nxos_lag_interfaces/tests/common/overridden.yaml
  tests/integration/targets/nxos_lag_interfaces/tests/common/replaced.yaml
Labels: mergeit

#466 [snmp_server] support new traps
  changelogs/fragments/nxos_snmp_server_1.yaml
  docs/cisco.nxos.nxos_snmp_server_module.rst
  plugins/module_utils/network/nxos/argspec/snmp_server/snmp_server.py
  plugins/module_utils/network/nxos/config/snmp_server/snmp_server.py
  plugins/module_utils/network/nxos/rm_templates/snmp_server.py
  plugins/modules/nxos_snmp_server.py
  tests/unit/modules/network/nxos/test_nxos_snmp_server.py
Labels: mergeit

#444 [snmp_server] fix (#443)
  changelogs/fragments/snmp_server_PR444.yaml
  plugins/module_utils/network/nxos/rm_templates/snmp_server.py
  tests/unit/modules/network/nxos/test_nxos_snmp_server.py
Labels: mergeit

#477 Bump min required netcommon
  changelogs/fragments/min_netcommon.yaml
  changelogs/fragments/netcommon_ref_update.yaml
  galaxy.yml
Labels: mergeit

#478 Prepare for release v3.0.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/fix_ci.yaml
  changelogs/fragments/lag_interfaces.yaml
  changelogs/fragments/min_netcommon.yaml
  changelogs/fragments/netcommon_ref_update.yaml
  changelogs/fragments/ntp.yaml
  changelogs/fragments/nxos_facts.yaml
  changelogs/fragments/nxos_file_copy.yaml
  changelogs/fragments/nxos_snmp_server.yaml
  changelogs/fragments/nxos_snmp_server_1.yaml
  changelogs/fragments/snmp_server_PR444.yaml
  changelogs/fragments/stderr.yaml
Labels: mergeit
