Repository ansible-collections/cisco.nxos, pull requests merged in 2023-08, with the labels that each got.

#728 disable auto changelog PR on merge
  .github/workflows/push.yml
Labels: skip-changelog

#732 Update all_green check
  .github/workflows/tests.yml
Labels: bug, skip-changelog

#731 [acls] Fix parsing error when ACE has source port range
  changelogs/fragments/fix_713.yaml
  plugins/module_utils/network/nxos/facts/acls/acls.py
  tests/unit/modules/network/nxos/test_nxos_acls.py
Labels: bug

#733 Added new codecov workflow
  changelogs/fragments/codecov_pr.yml
  codecov.yml
Labels: skip-changelog

#734 [interfaces] re-apply MTU when changing mode to L2
  changelogs/fragments/fix_730.yaml
  plugins/module_utils/network/nxos/config/interfaces/interfaces.py
  tests/unit/modules/network/nxos/test_nxos_interfaces.py
Labels: bug

#735 Update Docs with examples
  changelogs/fragments/_health_check_update_docs.yaml
  docs/cisco.nxos.nxos_bgp_address_family_module.rst
  docs/cisco.nxos.nxos_bgp_global_module.rst
  docs/cisco.nxos.nxos_bgp_neighbor_address_family_module.rst
  docs/cisco.nxos.nxos_bgp_templates_module.rst
  docs/cisco.nxos.nxos_ospf_interfaces_module.rst
  docs/cisco.nxos.nxos_ospfv2_module.rst
  docs/cisco.nxos.nxos_ospfv3_module.rst
  plugins/modules/nxos_bgp_address_family.py
  plugins/modules/nxos_bgp_global.py
  plugins/modules/nxos_bgp_neighbor_address_family.py
  plugins/modules/nxos_bgp_templates.py
  plugins/modules/nxos_ospf_interfaces.py
  plugins/modules/nxos_ospfv2.py
  plugins/modules/nxos_ospfv3.py
Labels: enhancement
