Repository ansible-collections/cisco.nxos, pull requests merged in 2023-09, with the labels that each got.

#738 fc_interfaces module for cisco mds
  README.md
  changelogs/fragments/nxos_mds_fc.yaml
  plugins/module_utils/network/nxos/argspec/fc_interfaces/__init__.py
  plugins/module_utils/network/nxos/argspec/fc_interfaces/fc_interfaces.py
  plugins/module_utils/network/nxos/config/fc_interfaces/__init__.py
  plugins/module_utils/network/nxos/config/fc_interfaces/fc_interfaces.py
  plugins/module_utils/network/nxos/facts/facts.py
  plugins/module_utils/network/nxos/facts/fc_interfaces/__init__.py
  plugins/module_utils/network/nxos/facts/fc_interfaces/fc_interfaces.py
  plugins/module_utils/network/nxos/rm_templates/fc_interfaces.py
  plugins/modules/nxos_fc_interfaces.py
  tests/unit/modules/network/nxos/test_nxos_fc_interfaces.py
Labels: feature

#745 [bgp_templates] Add support for safi evpn & send_community
  changelogs/fragments/bgp_templates.yaml
  docs/cisco.nxos.nxos_bgp_templates_module.rst
  plugins/module_utils/network/nxos/argspec/bgp_templates/bgp_templates.py
  plugins/module_utils/network/nxos/config/bgp_templates/bgp_templates.py
  plugins/module_utils/network/nxos/facts/bgp_templates/bgp_templates.py
  plugins/module_utils/network/nxos/rm_templates/bgp_templates.py
  plugins/modules/nxos_bgp_templates.py
  tests/unit/modules/network/nxos/test_nxos_bgp_templates.py
Labels: feature, bug

#748 [lag_interfaces] make 'force' option idempotent
  changelogs/fragments/lag_interfaces.yaml
  plugins/module_utils/network/nxos/config/lag_interfaces/lag_interfaces.py
  tests/integration/targets/nxos_lag_interfaces/tests/common/merged.yaml
  tests/integration/targets/nxos_lag_interfaces/tests/common/overridden.yaml
Labels: bug

#746 [bgp] add support for lesser used options
  changelogs/fragments/bgp_assorted.yaml
  docs/cisco.nxos.nxos_bgp_global_module.rst
  docs/cisco.nxos.nxos_bgp_neighbor_address_family_module.rst
  docs/cisco.nxos.nxos_fc_interfaces_module.rst
  plugins/module_utils/network/nxos/argspec/bgp_global/bgp_global.py
  plugins/module_utils/network/nxos/argspec/bgp_neighbor_address_family/bgp_neighbor_address_family.py
  plugins/module_utils/network/nxos/config/bgp_global/bgp_global.py
  plugins/module_utils/network/nxos/config/bgp_neighbor_address_family/bgp_neighbor_address_family.py
  plugins/module_utils/network/nxos/facts/bgp_global/bgp_global.py
  plugins/module_utils/network/nxos/facts/bgp_neighbor_address_family/bgp_neighbor_address_family.py
  plugins/module_utils/network/nxos/rm_templates/bgp_global.py
  plugins/module_utils/network/nxos/rm_templates/bgp_neighbor_address_family.py
  plugins/modules/nxos_bgp_global.py
  plugins/modules/nxos_bgp_neighbor_address_family.py
  plugins/modules/nxos_fc_interfaces.py
  tests/unit/modules/network/nxos/test_nxos_bgp_global.py
  tests/unit/modules/network/nxos/test_nxos_bgp_neighbor_address_family.py
Labels: feature

#752 DNM
  .github/workflows/ack.yml
Labels: bug

#750 [route_maps] support extcommunity rt option
  .github/workflows/ack.yml
  changelogs/fragments/route_maps.yaml
  docs/cisco.nxos.nxos_route_maps_module.rst
  plugins/module_utils/network/nxos/argspec/route_maps/route_maps.py
  plugins/module_utils/network/nxos/config/route_maps/route_maps.py
  plugins/module_utils/network/nxos/rm_templates/route_maps.py
  plugins/modules/nxos_route_maps.py
  tests/unit/modules/network/nxos/test_nxos_route_maps.py
Labels: feature, bug

#755 Remove python dependencies from bindep
  .github/workflows/ack.yml
  bindep.txt
Labels: skip-changelog

#657 [snmp_server] fix user negation when authentication options are present
  changelogs/fragments/snmp_server_fix.yml
  plugins/module_utils/network/nxos/rm_templates/snmp_server.py
  tests/unit/modules/network/nxos/test_nxos_snmp_server.py
Labels: bug

#756 Prepare for 5.2.0
  .ansible-lint-ignore
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/_health_check_update_docs.yaml
  changelogs/fragments/bgp_assorted.yaml
  changelogs/fragments/bgp_templates.yaml
  changelogs/fragments/codecov_pr.yml
  changelogs/fragments/fix_713.yaml
  changelogs/fragments/fix_730.yaml
  changelogs/fragments/lag_interfaces.yaml
  changelogs/fragments/nxos.yaml
  changelogs/fragments/nxos_mds_fc.yaml
  changelogs/fragments/route_maps.yaml
  changelogs/fragments/snmp_server_fix.yml
  galaxy.yml
Labels: skip-changelog

#761 [vtp_version] allow VTP version 3
  changelogs/fragments/vtp_version.yaml
  docs/cisco.nxos.nxos_vtp_version_module.rst
  galaxy.yml
  plugins/modules/nxos_vtp_version.py
Labels: feature

#760 [acls] update examples and use YAML output in them for better readibility
  .ansible-lint
  .ansible-lint-ignore
  changelogs/fragments/acls.yaml
  docs/cisco.nxos.nxos_acls_module.rst
  plugins/module_utils/network/nxos/facts/acls/acls.py
  plugins/modules/nxos_acls.py
  tests/config.yml
Labels: docs
