Repository ansible-collections/cisco.nxos, pull requests merged in 2024-01, with the labels that each got.

#791 [file_copy] timeout calculation fixes
  changelogs/fragments/file_copy.yaml
  plugins/action/nxos.py
Labels: bug

#802 Move platform guide to this repo
  README.md
  platform_guide.rst
Labels: docs, minor

#804 Fixes `module_defaults` being incorrectly applied to platform actions
  changelogs/fragments/module_defaults.yaml
  meta/runtime.yml
Labels: bug

#808 Prepare for v6.0.1
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/file_copy.yaml
  changelogs/fragments/module_defaults.yaml
Labels: skip-changelog

#809 Update version 6.0.1 in galaxy.yml
  galaxy.yml
Labels: skip-changelog
