Repository ansible-collections/cisco.nxos, pull requests merged in 2024-05, with the labels that each got.

#859 [static_routes] correctly generate commands when track param is specified
  changelogs/fragments/ana_442.yaml
  plugins/module_utils/network/nxos/facts/static_routes/static_routes.py
  plugins/module_utils/network/nxos/rm_templates/static_routes.py
  tests/unit/modules/network/nxos/test_nxos_static_routes.py
Labels: bug, safe to test

#856 [route_maps] Enable handling of route-maps without set/match
  changelogs/fragments/route_maps.yaml
  plugins/module_utils/network/nxos/config/route_maps/route_maps.py
  tests/unit/modules/network/nxos/test_nxos_route_maps.py
Labels: enhancement

#857 [l3_interfaces] fail if encapsulation exists on a different sub-interface.
  changelogs/fragments/nxos_l3_interfaces.yaml
  plugins/cliconf/nxos.py
  plugins/module_utils/network/nxos/config/l3_interfaces/l3_interfaces.py
Labels: bug, safe to test

#862 [cliconf] changes required after cliconfbase updates in ansible.netcommon#640
  plugins/cliconf/nxos.py
Labels: skip-changelog, safe to test
